development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://jfrupvcxdhujzq:0553fcfa26d8f752d0df893e8080641a09f90664fae1e60e650b03b5209a6103@ec2-75-101-142-91.compute-1.amazonaws.com:5432/de20dmerjmgvfp
  channel_prefix: nameofapp_production
